###
GET https://dummyjson.com/products?limit=10&skip=10&select=title,price

###
GET https://dummyjson.com/products

###
POST https://dummyjson.com/products/add
Content-Type: application/json

{
  "title": "Product 1",
  "price": 100
}

###
GET HTTP://LOCALHOST:3000/p